### ISSUE TITLE
CSP Headers

### ISSUE THREAD

**Issue by Firesphere** [lekoala/silverstripe-defer-backend#1]
Have you seen firesphere/silverstripe-cspheaders?

**Comment by lekoala** [comment]
I did ! actually i found myself having to add csp to a website and found that the strict-dynamic approach the easiest one. It works out of the box most of the time and this is why i decided to add it to this module. Because you need to have a dedicated requirements backend to inject the nonce on all scripts (i don't know how you manage to do it in your module... )

I haven't check for any compatibility issue, ideally it should be possible to use both modules depending on your needs

**Comment by Firesphere** [comment]
I inject a different backend indeed, which, depending on the configuration, inserts nonces, adds hashes, and if wished for, also adds SRI integrity checks (Although, ever since the move to `public/_resources`, it has a bit of trouble calculating self-hosted SRI's)

**Comment by lekoala** [comment]
What would be ideal is that we could set some extension to the requirements backend ourself, having to override the base class feels like a missed opportunity on the framework side.
In a world with infinite free time I would certainly send a pull request :-)

Let me know if I can do anything regarding your module, we can mention it in the readme for those who want a more complete solution for csp

**Comment by Firesphere** [comment]
I've been trying to get it to work properly, but so far, only am able to make it work using the injector and making the PHPDebugBar class dynamic for parts of it.

Happy to look a bit more in to it, as I'm having a break the next few weeks. But obviously, not gonna waste all my spare time on it.

I think a simple guide, and a hook, would be a great idea.

When it comes to full configurable CSP, I understand your intentions, and it's up to you to suggest it or not :)

I'll probably push up tomorrow or Friday, and reply here with the branch I'm gonna be using from both the fork and my own work :)

**Comment by lekoala** [comment]
Or maybe it's easier to simply defer everything on your side and wrap
inline scripts. Sometimes copy pasting is a good option if the flexibility
is not there.

**Comment by lekoala** [comment]
@Firesphere  i'm closing this, i've aded the ability to set the nonce from an external source (other module for example) that should be enough to avoid conflicts. otherwise it's as simple as leaving the options disabled :)
